spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring-security?useSSL=false
    username: root
    password: Huawei@123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8888