spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring-oauth2?useSSL=false
    username: root
    password: Huawei@123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: auth-service

server:
  port: 5000
  servlet:
    context-path: /uaa

eureka:
  client:
    service-url:
      # 配置注册中心地址
      default-zone: http://localhost:8761/eureka/
  instance:
    # 配置在注册中心的显示，这里和Swagger结合在了一起
    status-page-url: http://${spring.cloud.client.ip-address}:${server.port}
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}