eureka:
  client:
    service-url:
      # 配置注册中心地址
      default-zone: http://localhost:8761/eureka/
  instance:
    # Zuul在注册中心的显示
    status-page-url: http://${spring.cloud.client.ip-address}:${server.port}
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}

server:
  port: 9000

spring:
  application:
    name: api-gateway

zuul:
  # 处理HTTP请求头Cookie为空的问题
  sensitive-headers: