spring:
  application:
    name: log-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sys-log?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: Huawei@123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    publisher-confirms: true
    virtual-host: /

server:
  port: 9997

# service registry
eureka:
  instance:
    ip-address: 127.0.0.1
    port: 8761
    status-page-url: http://${spring.cloud.client.ipAddress}:${server.port}/swagger-ui.html
    instance-id: ${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.ip-address}:${eureka.instance.port}/eureka/

management:
  security:
    enabled: false