eureka:
  client:
    service-url:
      # 配置注册中心地址
      default-zone: http://localhost:8761/eureka/
  instance:
    # 配置在注册中心的显示，这里和Swagger结合在了一起
    status-page-url: http://${spring.cloud.client.ip-address}:${server.port}/swagger-ui.html
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}

server:
  port: 8764

spring:
  application:
    name: order-service
